ROUNDING_PRECISION : int = 3
MAP_SCALE : float = 100.0

NUM_TEAMS = 20
# CONSTRAINTS 1+2
TEAMS_PER_GROUP = 4

NUM_GROUPS = int(NUM_TEAMS / TEAMS_PER_GROUP)

s = 6  # Anzahl Spieltage

GAMES_PER_DAY_MIN = 3
GAMES_PER_DAY_MAX = 3

NUM_GAMES_AGAINST_GROUP_MEMBERS = 2
NUM_GAMES_AGAINST_OTHERS = 1